version: '3.5'

networks:
#  frontend:
#    name: fronted
#    driver: bridge
  backend:
    name: backend
    driver: bridge

volumes:
  db_data:
    driver: local

services:
  php_apache:
    build:
      context: ./php_apache
    ports:
      - 80:80
      - 443:443
        #    env_file: .env
        #    environment:
        #      DATABASE_HOST: db
        #    depends_on:
        #      - db
        #    volumes:
        #      - ./data/html:/var/www/html
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    networks:
      - backend

  mysql:
    build:
      context: ./mysql
      #env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        #- TZ=${WORKSPACE_TIMEZONE}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      #- ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    networks:
      - backend
